In [1]:
import pandas as pd

customer_df = pd.read_csv(
    "../data/processed/rfm_customers.csv"
)

customer_df.head()

   CustomerID  Recency  Frequency  Monetary
0     12346.0      326          2      0.00
1     12347.0        2          7   4310.00
2     12348.0       75          4   1797.24
3     12349.0       19          1   1757.55
4     12350.0      310          1    334.40

In [2]:
print(customer_df.columns)

Index(['CustomerID', 'Recency', 'Frequency', 'Monetary'], dtype='str')

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

# Create churn label
customer_df["Churn"] = (
    customer_df["Recency"] > 90
).astype(int)

# Features
X = customer_df[
    ["Recency", "Frequency", "Monetary"]
]

# Target
y = customer_df["Churn"]

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Train model
model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

# Predictions
preds = model.predict(X_test)

# Evaluation
print(classification_report(y_test, preds))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       594
           1       1.00      1.00      1.00       281

    accuracy                           1.00       875
   macro avg       1.00      1.00      1.00       875
weighted avg       1.00      1.00      1.00       875

In [4]:
import pandas as pd

importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": model.feature_importances_
})

importance.sort_values(
    by="Importance",
    ascending=False
)

     Feature  Importance
0    Recency    0.881103
1  Frequency    0.062992
2   Monetary    0.055905

In [5]:
from joblib import dump

dump(
    model,
    "../models/churn_model.joblib"
)

['../models/churn_model.joblib']

In [6]:
customer_df.to_csv(
    "../data/processed/customer_churn.csv",
    index=False
)