In [1]:
import pandas as pd

In [2]:
sales = pd.read_csv(
    "../data/processed/daily_sales.csv"
)

sales.head()

  InvoiceDate   Revenue
0  2010-12-01  45867.26
1  2010-12-02  45656.47
2  2010-12-03  22553.38
3  2010-12-05  30970.28
4  2010-12-06  30258.77

In [3]:
forecast = pd.read_csv(
    "../data/processed/forecast_30_days.csv"
)

forecast.head()

           ds          yhat
0  2010-12-01  24355.090268
1  2010-12-02  31316.088857
2  2010-12-03  19857.210247
3  2010-12-05  10886.000829
4  2010-12-06  22171.674093

In [4]:
customers = pd.read_csv(
    "../data/processed/customer_segments.csv"
)

customers.head()

   CustomerID  Recency  Frequency  Monetary  Cluster  DBSCAN
0     12346.0      326          2      0.00        1       0
1     12347.0        2          7   4310.00        3       0
2     12348.0       75          4   1797.24        3       0
3     12349.0       19          1   1757.55        3       0
4     12350.0      310          1    334.40        1       0

In [5]:

print("Sales:", sales.shape)
print("Forecast:", forecast.shape)
print("Customers:", customers.shape)

Sales: (305, 2)
Forecast: (335, 2)
Customers: (4372, 6)

In [6]:
total_revenue = sales["Revenue"].sum()

avg_daily_revenue = sales["Revenue"].mean()

print("Total Revenue:", total_revenue)
print("Average Daily Revenue:", avg_daily_revenue)

Total Revenue: 8278519.424
Average Daily Revenue: 27142.686636065573

In [7]:

sales.to_csv(
    "../dashboard/sales_dashboard.csv",
    index=False
)

forecast.to_csv(
    "../dashboard/forecast_dashboard.csv",
    index=False
)

customers.to_csv(
    "../dashboard/customer_dashboard.csv",
    index=False
)